spring:
  profiles:
    active: peer1
  application:
    name: ereka-server
---
spring:
  profiles: peer1
server:
  port: 8800
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0


---
spring:
  profiles: peer2
server:
  port: 8801
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
