spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://localhost:8083
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1
      - id: host_route
        uri: http://localhost:8081
        predicates:
        - Path=/b/**
        filters:
        - StripPrefix=1